/* eslint-disable */
// Generated by Wrangler by running `wrangler types services/runner/worker-configuration.d.ts --config services/runner/wrangler.jsonc --env-interface RunnerEnv --include-runtime=false --strict-vars=false` (hash: 9d8d24e94b975ab5f30bce4a555aec30)
interface __BaseEnv_RunnerEnv {
	RUNNER_OWNER_ID: string;
	RUNNER_ENGINE_VERSION: string;
	RUNNER_HMAC_SECRET: string;
	PAPER_RUNNERS: DurableObjectNamespace<import("./src/worker").OwnerPaperRunner>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "OwnerPaperRunner";
	}
	interface Env extends __BaseEnv_RunnerEnv {}
}
interface RunnerEnv extends __BaseEnv_RunnerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RUNNER_OWNER_ID" | "RUNNER_ENGINE_VERSION" | "RUNNER_HMAC_SECRET">> {}
}
