'use client';
import {useId} from 'react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import type {Point} from '@/lib/market/types';
export function Sparkline({points,down=false}:{points:Point[];down?:boolean}){
 const id=useId().replaceAll(':','');if(points.length<2)return <div className="spark-empty">Gathering price history <span>•••</span></div>;
 const min=Math.min(...points.map(p=>p.price)),max=Math.max(...points.map(p=>p.price));const range=Math.max(.03,max-min);const first=points[0].time,last=points.at(-1)!.time;
 const coords=points.map(p=>`${((p.time-first)/Math.max(1,last-first)*300).toFixed(1)},${(65-(p.price-min)/range*52).toFixed(1)}`);const color=down?'#f27d86':'#b8f569';
 return <svg viewBox="0 0 300 78" preserveAspectRatio="none" className="spark" role="img" aria-label={`Price trend from ${(points[0].price*100).toFixed(1)} to ${(points.at(-1)!.price*100).toFixed(1)} percent`}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".18"/><stop offset="100%" stopColor={color} stopOpacity="0"/></linearGradient></defs><path d={`M0,78 L${coords.join(' L')} L300,78 Z`} fill={`url(#${id})`}/><polyline points={coords.join(' ')} fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>;
}
export function BeliefChart({points,money=false}:{points:Point[];money?:boolean}){if(points.length<2)return <div className="chart-empty"><span>History starts here.</span><p>{money?'Your first paper trade will start the story.':'Waiting for at least two genuine price observations.'}</p></div>;
 return <div className="big-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={points} margin={{top:15,right:15,bottom:0,left:0}}><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b8f569" stopOpacity={.18}/><stop offset="100%" stopColor="#b8f569" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#2b3030" strokeDasharray="3 5"/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} scale="time" tickFormatter={t=>new Date(t).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} minTickGap={60} tick={{fill:'#8f9996',fontSize:12}} axisLine={false} tickLine={false}/><YAxis domain={money?['auto','auto']:[0,1]} tickFormatter={v=>money?`$${v}`:`${Math.round(v*100)}%`} tick={{fill:'#8f9996',fontSize:12}} width={48} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#202724',border:'1px solid #3a433d',borderRadius:10,color:'#fff'}} labelFormatter={t=>new Date(Number(t)).toLocaleString()} formatter={v=>[money?`$${Number(v).toFixed(2)}`:`${(Number(v)*100).toFixed(1)}%`,money?'Paper equity':'YES display price']}/><Area type="linear" dataKey="price" stroke="#b8f569" strokeWidth={2.5} fill="url(#chart-fill)" isAnimationActive={false} connectNulls={false}/></AreaChart></ResponsiveContainer></div>;
}
