'use client';
import {ArrowUpRight,ArrowDownRight,ArrowRight,Bookmark,ChevronRight,HelpCircle} from 'lucide-react';
import type {Market} from '@/lib/market/types';
import {Sparkline} from './chart';
export const cents=(p:number|null)=>p===null?'—':`${(p*100).toFixed(1).replace(/\.0$/,'')}¢`;
export const number=(p:number)=>p.toFixed(1).replace(/\.0$/,'');
export function gameTime(start:string){if(!start)return 'Time not supplied';return new Date(start).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
export function MarketCard({m,watched,onWatch,onOpen,onExplain,beginner,watchPrice}:{m:Market;watched:boolean;onWatch:()=>void;onOpen:()=>void;onExplain:()=>void;beginner:boolean;watchPrice?:number|null}){
 const first=m.history[0],last=m.history.at(-1);const change=first&&last?(last.price-first.price)*100:null;const down=change!==null&&change<-.05;const signal=m.signals[0];const spread=m.ask!==null&&m.bid!==null?(m.ask-m.bid)*100:null;
 const Icon=change===null||Math.abs(change)<.05?ArrowRight:down?ArrowDownRight:ArrowUpRight;
 return <article className={`market-card ${down?'falling':''}`}><div className="card-meta"><span className="league-tag">{m.league}</span><span>{gameTime(m.start)}</span><button className={`icon-button ${watched?'saved':''}`} onClick={onWatch} aria-label={watched?'Unwatch market':'Watch market'}><Bookmark size={18} fill={watched?'currentColor':'none'}/></button></div><button className="matchup-button" onClick={onOpen}><h3>{m.teams.length===2?<>{m.teams[0].name}<span className="versus"> vs </span>{m.teams[1].name}</>:m.game}</h3></button><div className="outcome-label">{m.title}</div><div className="price-chart"><div><div className="big-price">{cents(m.price)}</div><div className="implied">{m.price!==null?`≈ ${number(m.price*100)}% ${beginner?'chance':'implied'}`:'No current offer'}</div></div><Sparkline points={m.history} down={down}/></div><div className={`movement ${down?'down':change===null||Math.abs(change)<.05?'neutral':'up'}`}><Icon size={20}/><strong>{change===null?'History warming up':`${change>=0?'+':''}${number(change)} points`}</strong><span>{first&&last?`in ${Math.max(1,Math.round((last.time-first.time)/60000))} min`:'No invented movement'}</span></div>{watchPrice!=null&&m.price!==null&&<div className="watch-change">{number((m.price-watchPrice)*100)} points since watched</div>}<div className="card-micro"><span>Spread <b>{spread===null?'—':`${number(spread)}¢`}</b><span className={spread!==null&&spread>=5?'amber':''}>{spread===null?'unavailable':spread>=5?'wide':'tight'}</span></span><span>Activity <b>{m.signals.some(s=>s.type==='UNUSUAL ACTIVITY')?'BURST':'collecting'}</b></span></div><div className={`reason-strip ${signal?'':'quiet'}`}><span className={`signal-dot ${down?'red':''}`}/><span>{signal?.type||'ON THE RADAR'}</span><button onClick={onExplain} aria-label="Explain this signal"><HelpCircle size={16}/></button></div><p className="card-reason">{signal?.reason||'No scanner threshold crossed. Open the chart to see the market’s recent view.'}</p><div className="card-actions"><button onClick={onExplain}>Explain this <HelpCircle size={14}/></button><button onClick={onOpen}>Open market <ChevronRight size={16}/></button></div></article>;
}
