'use client';

import {tennisCommandId} from './command-id';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Activity,ArrowUpRight,ChevronDown,Clock3,ExternalLink,FlaskConical,LoaderCircle,Pause,Play,Radio,RefreshCw,RotateCcw,Square,TriangleAlert,X} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import type {TennisLeague,TennisMarket,TennisSession} from '@/lib/tennis/types';
import {useTennis} from './use-tennis';
import {TennisMarketDialog} from './market-dialog';
import {TennisPriceChart,TennisSparkline} from './price-chart';
import './tennis.css';

const money=(value:number)=>`${value<0?'−':''}$${Math.abs(value).toFixed(2)}`;
const signed=(value:number)=>`${value>0?'+':''}${money(value)}`;
const cents=(value:number|null)=>value===null?'—':`${(value*100).toFixed(value*100%1<.01?0:1)}¢`;
const age=(time:number,now:number)=>time<=0?'not observed':now-time<10000?'just now':now-time<60000?`${Math.floor((now-time)/1000)}s ago`:`${Math.floor((now-time)/60000)}m ago`;
const time=(value:number)=>new Date(value).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});

function marketPoints(market:TennisMarket,session:TennisSession|null) {
  return market.history.length>=2?market.history:session?.histories[`${market.slug}:YES`]??market.history;
}

function MarketCard({market,session,now,onOpen}:{market:TennisMarket;session:TennisSession|null;now:number;onOpen:()=>void}) {
  const points=marketPoints(market,session),first=points[0],last=points[points.length-1];
  const delta=first&&last?(last.price-first.price)*100:null;
  const spread=market.ask!==null&&market.bid!==null?market.ask-market.bid:null;
  const price=market.price,stale=now-market.observedAt>30000;
  const state=session?.signals[`${market.slug}:YES`];
  const start=new Date(market.startTime);
  const suspended=/sus|suspend|delay|interrupt/i.test(market.period??'');
  return <article className="tennis-card">
    <div className="tennis-card-meta"><span className="tennis-tour">{market.league}</span><span className={`tennis-dot ${market.live?'is-live':''}`}/><span>{suspended?'SUSPENDED':market.live?'IN PLAY':market.ended?'ENDED':'UPCOMING'}</span><time>{market.live&&market.score?market.score:Number.isNaN(start.getTime())?'Time unavailable':start.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time></div>
    <button className="tennis-matchup" onClick={onOpen} aria-label={`Open ${market.yesName} versus ${market.noName}`}><strong>{market.yesName}</strong><span>vs.</span><strong>{market.noName}</strong></button>
    <div className="tennis-card-prices"><div><div className="tennis-main-price">{price===null?'—':(price*100).toFixed(price*100%1<.01?0:1)}{price!==null&&<small>¢</small>}</div><p>{market.yesName.split(' ').at(-1)} · market price</p></div><div><b>{cents(market.ask)}</b><p>to buy</p></div></div>
    <TennisSparkline points={points}/>
    <div className="tennis-movement"><span className={delta!==null&&delta<0?'tennis-negative':delta!==null&&delta>0?'tennis-positive':''}>{delta===null||points.length<2?'History building':`${delta>0?'↗ +':delta<0?'↘ ':'→ '}${delta.toFixed(1)} points`}</span><span>{points.length>1?`over ${Math.max(1,Math.round((last.time-first.time)/60000))} min`:stale?'Quote needs refresh':age(market.observedAt,now)}</span></div>
    <div className="tennis-card-footer"><span>{state?.phase==='DIP'?'Dip observed':state?.phase==='RECOVERING'?'Recovery observed':spread===null?'No two-sided quote':`Spread ${cents(spread)}`}{stale?' · stale':''}</span><button onClick={onOpen}>Chart & paper trade <ArrowUpRight size={13}/></button></div>
  </article>;
}

export function TennisDashboard() {
  const bot=useTennis();
  const {session,catalog,now}=bot;
  const [beginner,setBeginner]=useState(true),[filter,setFilter]=useState<'ALL'|TennisLeague>('ALL');
  const [selected,setSelected]=useState<string|null>(null),[resetOpen,setResetOpen]=useState(false),[resetBalance,setResetBalance]=useState(100);
  const [entryOverride,setEntryOverride]=useState<{id:string;amount:number}|null>(null),[showAll,setShowAll]=useState(false),[activityTab,setActivityTab]=useState<'decisions'|'trades'|'balance'>('decisions');
  const [settingsOpen,setSettingsOpen]=useState(false);
  useEffect(()=>{queueMicrotask(()=>{try{setBeginner(localStorage.getItem('dugout-tennis-beginner')!=='false');}catch{/* Optional preference. */}});},[]);
  const entryBudget=entryOverride?.id===session?.id&&entryOverride?entryOverride.amount:session?.config.entryBudget??5;
  const open=session?.positions.filter(position=>position.status==='open')??[];
  const closed=session?.positions.filter(position=>position.status!=='open')??[];
  const liquidCash=(session?.cash??0)+open.reduce((sum,position)=>sum+(position.netLiquidationValue??0),0);
  const incompleteMark=open.some(position=>position.netLiquidationValue===null||position.liquidationQuantity+1e-7<position.quantity||!position.markedAt||now-position.markedAt>15000);
  const pnl=session?liquidCash-session.config.startingCash:0;
  const feedUnavailable=!!bot.feedError||!!catalog?.errors.length;
  const markets=(catalog?.markets??[]).filter(market=>filter==='ALL'||market.league===filter);
  const selectedMarket=catalog?.markets.find(market=>market.slug===selected)??session?.positions.find(position=>position.slug===selected)?.market??null;
  const isRunning=session?.status==='running',isPaused=session?.status==='paused',isIdle=session?.status==='idle',isStopped=session?.status==='stopped';
  const tickStale=!!session&&['running','paused','stopping'].includes(session.status)&&now-session.lastTickAt>20000;
  const status=!session?'Connecting':session.status==='stopping'?'Exiting position':isStopped?'Stopped':tickStale?'Waiting for a fresh check':isPaused?'Entries paused':session.pending?'Order pending':isRunning?(open.length?'Managing position':'Scanning'):'Ready';
  const reason=!session?'Loading your saved paper session…':!bot.visible?'Page is hidden. Live checks resume when you return.':tickStale?'The last bot check is older than 20 seconds. No fills are made using stale data.':session.lastReason;
  const decisions=[...(session?.decisions??[])].reverse();
  const seen=new Set<string>();
  const unique=decisions.filter(decision=>{const key=`${decision.slug}:${decision.side}:${decision.code}`;if(seen.has(key)&&['WAIT','SKIP'].includes(decision.action))return false;seen.add(key);return true;}).slice(0,showAll?60:6);
  const ledger=[...(session?.ledger??[])].reverse().slice(0,showAll?60:6);
  const labelFor=(slug:string,side:'YES'|'NO')=>{const market=catalog?.markets.find(item=>item.slug===slug)??session?.positions.find(position=>position.slug===slug)?.market;return market?(side==='YES'?market.yesName:market.noName):slug||'Paper session';};
  const reset=async()=>{const ok=await bot.perform({action:'reset',bankroll:resetBalance,commandId:tennisCommandId()});if(ok)setResetOpen(false);};
  return <div className="tennis-app">
    <header className="tennis-header"><Link className="tennis-logo" href="/" aria-label="Dugout home"><span className="tennis-logo-mark"><Activity size={20}/></span>dugout<span style={{color:'#c2f477',marginLeft:-8}}>.</span></Link><div className="tennis-header-actions"><span className="tennis-paper-pill"><FlaskConical size={12}/>PAPER TRADING</span><label className="tennis-mode" htmlFor="tennis-beginner">Beginner mode<Switch id="tennis-beginner" checked={beginner} onCheckedChange={value=>{setBeginner(value);try{localStorage.setItem('dugout-tennis-beginner',String(value));}catch{/* Optional preference. */}}}/></label></div></header>
    <main className="tennis-main">
      <div className="tennis-heading"><div><span className="tennis-kicker">TENNIS · ATP & WTA</span><h1>Catch the recovery.</h1>{beginner&&<p>Real tennis markets. A fake balance. Automatic paper entries and exits.</p>}</div><div className="tennis-feed-indicator"><span className={`tennis-dot ${bot.streamStatus==='live'?'is-live':'is-waiting'}`}/>{bot.streamStatus==='live'?'Live Polymarket US stream':bot.streamStatus==='connecting'?'Connecting live stream…':'Polymarket US · REST checks'}{catalog&&<span>· {age(catalog.updatedAt,now)}</span>}</div></div>
      {bot.error&&!selected&&<div className="tennis-error" role="alert"><TriangleAlert size={16}/><span>{bot.error}</span><button aria-label="Dismiss error" onClick={bot.clearError}><X size={15}/></button></div>}
      <section className="tennis-command" aria-label="Paper bot controls">
        <div className="tennis-command-left"><div className="tennis-status-row"><span className="tennis-section-label">PRICE RECOVERY · PAPER BOT</span><span className="tennis-status"><span className={`tennis-dot ${isRunning&&!tickStale?'is-live':'is-waiting'}`}/>{status}</span></div>
          <div className="tennis-controls">{isIdle?<button className="tennis-primary" disabled={bot.busy||!session||entryBudget<1||entryBudget>Math.min(100,session.config.startingCash*.2)} onClick={()=>void bot.perform({action:'start',config:{entryBudget},commandId:tennisCommandId()})}><Play size={17}/>{bot.busy?'Starting…':'Start paper bot'}</button>:isStopped?<button className="tennis-primary" disabled={bot.busy||open.length>0} onClick={()=>{setResetBalance(session?.config.startingCash??100);setResetOpen(true);}}><RotateCcw size={16}/>New paper run</button>:<button className="tennis-primary" disabled={bot.busy||!session||session.status==='stopping'} onClick={()=>void bot.perform({action:isPaused?'resume':'pause',commandId:tennisCommandId()})}>{bot.busy?<LoaderCircle size={17}/>:isPaused?<Play size={17}/>:<Pause size={17}/>} {isPaused?'Resume bot':'Pause entries'}</button>}
          {!isIdle&&!isStopped&&session&&<button className="tennis-secondary" disabled={bot.busy||session.status==='stopping'} onClick={()=>void bot.perform({action:'stop',commandId:tennisCommandId()})}><Square size={13}/>Stop & exit</button>}
          {!session&&<button className="tennis-secondary" onClick={()=>void bot.reloadAccount()}><RefreshCw size={14}/>Reconnect</button>}</div>
          <p className="tennis-reason" role="status">{reason}</p><div className="tennis-runtime"><Clock3 size={12}/>Runs while this page is open and visible · paper only</div>{beginner&&isPaused&&open.length>0&&<p className="tennis-order-help">Exits are still checked. Pause only blocks new entries.</p>}
        </div>
        <div className="tennis-command-right"><span className="tennis-section-label">{incompleteMark?'CASH + PRICED EXIT SIZE':'PAPER BALANCE'}</span><strong className="tennis-balance">{session?money(liquidCash):'—'}</strong><span className={`tennis-pnl ${pnl<0?'tennis-negative':'tennis-positive'}`}>{session?`${signed(pnl)} ${incompleteMark?'· some holdings unpriced':'since start'}`:'Loading fake balance'}</span><div className="tennis-money-meta"><div>Available cash<strong>{session?money(session.cash):'—'}</strong></div><div>Bot entry<strong>{session?money(isIdle?entryBudget:session.config.entryBudget):'—'}</strong></div><button className="tennis-link" disabled={!session||bot.busy||open.length>0||!!session?.pending} title={open.length?'Close positions before resetting':undefined} onClick={()=>{setResetBalance(session?.config.startingCash??100);setResetOpen(true);}}>Reset balance</button></div></div>
      </section>
      {!!session?.pending&&<div className="tennis-notice" role="status"><Clock3 size={14}/>{session.pending.action==='BUY'?'Paper entry':'Paper exit'} queued · waiting for a fresh book after {session.config.executionDelayMs/1000}s execution delay.</div>}
      {open.length>0&&<section className="tennis-position-list" aria-label="Open paper positions"><h2 className="tennis-open-title">Your open trade</h2>{open.map(position=>{const marked=position.netLiquidationValue!==null&&!!position.markedAt&&now-position.markedAt<=15000;const returnValue=marked?position.netLiquidationValue!-position.costBasis:null;const partial=position.liquidationQuantity+1e-7<position.quantity;return <article className="tennis-position" key={position.id}><div><span className="tennis-section-label">{position.league} · {position.side} · PAPER</span><h3>{position.name}</h3><p>{position.quantity.toFixed(2)} contracts · {money(position.costBasis)} remaining cost</p></div><div className="tennis-position-return"><strong className={returnValue!==null&&returnValue<0?'tennis-negative':'tennis-positive'}>{returnValue===null?'—':signed(returnValue)}</strong><small>{!marked?'Waiting for fresh exit value':partial?'Only part can sell now':'Net P/L if filled now'}</small></div><button className="tennis-secondary" disabled={bot.busy||session?.pending?.action==='SELL'} onClick={()=>void bot.perform({action:'close',positionId:position.id,commandId:tennisCommandId()})}>{session?.pending?.action==='SELL'?'Exit pending…':'Paper exit now'}<ArrowUpRight size={15}/></button></article>;})}</section>}
      <div className="tennis-feed-heading"><h2>On the court<span className="tennis-count">{catalog?`${markets.length} ${markets.length===1?'market':'markets'}`:'Loading matches'}</span></h2><div className="tennis-feed-tools"><div className="tennis-filter" role="group" aria-label="Filter tennis tour">{([{value:'ALL',label:'All tennis'},{value:'ATP',label:'Men · ATP'},{value:'WTA',label:'Women · WTA'}] as const).map(item=><button key={item.value} aria-pressed={filter===item.value} onClick={()=>setFilter(item.value)}>{item.label}</button>)}</div><button className="tennis-refresh" aria-label="Refresh tennis markets" title="Refresh tennis markets" disabled={bot.refreshing} onClick={()=>void bot.refresh()}><RefreshCw size={16} className={bot.refreshing?'spin':''}/></button></div></div>
      {(bot.feedError||catalog?.errors.length!==0&&catalog?.errors.length)&&<div className="tennis-error" role="alert"><TriangleAlert size={16}/><span>{bot.feedError||catalog?.errors.join(' ')}</span></div>}
      <section className="tennis-market-grid" aria-label="Real tennis markets">{bot.loading?[0,1,2].map(index=><div className="tennis-loading-card" key={index}><LoaderCircle size={15} className="spin"/>Finding real tennis markets…</div>):markets.length?markets.map(market=><MarketCard market={market} session={session} now={now} key={market.slug} onOpen={()=>setSelected(market.slug)}/>):<div className="tennis-empty"><Radio size={30}/><h3>{feedUnavailable?'Tennis feed unavailable':'No open tennis markets right now.'}</h3><p>{feedUnavailable?'The feed could not be loaded. Your paper account is saved; retry when the connection returns.':`Polymarket US has no ${filter==='ALL'?'ATP or WTA':filter} markets in the current response. The bot will wait for real markets.`}</p><button className="tennis-secondary" disabled={bot.refreshing} onClick={()=>void bot.refresh()}><RefreshCw size={13}/>Check again</button></div>}</section>
      <div className="tennis-feed-note"><span>{beginner?'These are markets to inspect, not picks or recommendations.':''}</span><span>Streams up to 12 matches · REST fallback watches 4</span></div>
      <section className="tennis-activity" aria-label="Paper session results"><div className="tennis-activity-head"><div><h2>Your experiment</h2><div className="tennis-subtabs" role="group" aria-label="Experiment view">{([{id:'decisions',label:'Why no trade?'},{id:'trades',label:`Trades · ${session?.ledger.length??0}`},{id:'balance',label:'Balance'}] as const).map(tab=><button key={tab.id} aria-pressed={activityTab===tab.id} onClick={()=>setActivityTab(tab.id)}>{tab.label}</button>)}</div></div>{activityTab!=='balance'&&<button className="tennis-link" onClick={()=>setShowAll(!showAll)}>{showAll?'Show less':'Show all'}</button>}</div>
      {activityTab==='balance'?<><TennisPriceChart points={session?.equity??[]} currency/><div className="tennis-feed-note"><span>{closed.length} closed positions · {session?.evaluated??0} quote evaluations</span><span>Fees included in simulated fills</span></div></>:activityTab==='decisions'?unique.length?<div className="tennis-activity-list">{unique.map(decision=><div className="tennis-activity-row" key={decision.id}><span className={`tennis-action-badge ${decision.action==='BUY'?'is-buy':decision.action==='SELL'?'is-sell':''}`}>{decision.action}</span><div><strong>{labelFor(decision.slug,decision.side)}</strong><p>{decision.reason}</p></div><time>{time(decision.time)}</time></div>)}</div>:<div className="tennis-empty-activity">{isRunning?'Collecting the first observations. Every decision will appear here.':'Start a paper run to see exactly what the bot accepts and skips.'}</div>:ledger.length?<div className="tennis-activity-list">{ledger.map(entry=><div className="tennis-activity-row" key={entry.id}><span className={`tennis-action-badge ${entry.action==='BUY'?'is-buy':'is-sell'}`}>{entry.action}</span><div><strong>{labelFor(entry.slug,entry.side)} · {signed(entry.cashDelta)} cash</strong><p>{entry.source==='MANUAL'?'Manual':'Bot'} · {entry.execution?`${entry.execution.filledQty.toFixed(2)} contracts at ${cents(entry.execution.averagePrice)} · ${money(entry.execution.fees)} fees · ${entry.execution.status}`:'Settlement recorded'}{entry.action!=='BUY'?` · realized ${signed(entry.realizedPnl)}`:''}</p>{!beginner&&entry.quotedPrice!==undefined&&<p>Quoted {cents(entry.quotedPrice)} → filled {cents(entry.actualPrice??null)} · {((entry.executionDelayMs??0)/1000).toFixed(1)}s delay</p>}</div><time>{time(entry.time)}</time></div>)}</div>:<div className="tennis-empty-activity">No paper fills yet. Open a match to try a manual paper trade, or let the bot watch for its setup.</div>}</section>
      <details className="tennis-strategy" open={settingsOpen} onToggle={event=>setSettingsOpen(event.currentTarget.open)}><summary>Strategy & run settings<ChevronDown size={15}/></summary><div className="tennis-strategy-body"><div><h3>Price recovery · experimental v1</h3><p>{beginner?'Observe a drop from the recent price baseline. Wait for both the price and buyers to recover, then attempt a paper buy. Exit using the actual available buyers, with fees included.':'Median baseline → dip → buyer + price confirmation → delayed IOC entry → net-return exit.'}</p><p style={{marginTop:8}}>Profitability is unproven. No tennis outcome model or injury advantage is claimed.</p>{isIdle&&<label className="tennis-order-label" style={{marginTop:15}}>Bot amount per trade <input aria-label="Bot amount per trade" type="number" min="1" step=".01" max={Math.min(100,(session?.config.startingCash??100)*.2)} value={entryBudget} onChange={event=>setEntryOverride({id:session?.id??'',amount:Number(event.target.value)})} style={{width:80,padding:'6px 8px',background:'#15210e',border:'1px solid #466035',borderRadius:5}}/></label>}</div><dl><div><dt>Dip / confirmed recovery</dt><dd>{session?.config.declinePoints??3}¢ / {session?.config.recoveryPoints??1}¢</dd></div><div><dt>Target / loss exit attempt</dt><dd>+{((session?.config.targetReturn??.03)*100).toFixed(0)}% / −{((session?.config.stopReturn??.08)*100).toFixed(0)}%</dd></div><div><dt>Maximum planned hold</dt><dd>{Math.round((session?.config.maxHoldMs??120000)/60000)} minutes</dd></div><div><dt>Spread limit</dt><dd>{session?.config.maxSpreadPoints??2}¢</dd></div><div><dt>Paper execution delay</dt><dd>{(session?.config.executionDelayMs??1000)/1000}s + next fresh book</dd></div><div><dt>Positions at once</dt><dd>1 · bot 20% / manual 25% cap</dd></div><div><dt>Session rules</dt><dd>{isIdle?'Editable before start':'Frozen for this run'}</dd></div><div><dt>Runtime</dt><dd>Browser open + visible</dd></div><div><dt>Recorded evidence</dt><dd><a className="tennis-link" href="/api/tennis/session?export=1" download>Export this paper run</a></dd></div></dl></div></details>
    </main>
    <footer className="tennis-footer"><span>Paper research. Fills and fees are estimates. Exits depend on available buyers.</span><a href="/sports">MLB & NFL workspace <ExternalLink size={11}/></a></footer>
    <TennisMarketDialog key={selected??'none'} market={selectedMarket} session={session} beginner={beginner} now={now} busy={bot.busy} onClose={()=>setSelected(null)} onAction={bot.perform} error={bot.error}/>
    <Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent className="tennis-market-dialog"><DialogTitle className="tennis-dialog-title">Start with fake money.</DialogTitle><DialogDescription className="tennis-dialog-description">Choose $5–$1,000 for a new paper run. Reset starts a fresh run and archives the previous balance and history. Close all positions first.</DialogDescription><div className="tennis-reset-form"><label htmlFor="tennis-reset-balance">Starting paper balance</label><input className="tennis-reset-input" id="tennis-reset-balance" type="number" min="5" max="1000" step="1" value={resetBalance} onChange={event=>setResetBalance(Number(event.target.value))}/><div className="tennis-amounts">{[5,10,100].map(value=><button key={value} aria-pressed={resetBalance===value} onClick={()=>setResetBalance(value)}>${value}</button>)}</div>{bot.error&&<div className="tennis-dialog-error" role="alert">{bot.error}</div>}<div className="tennis-reset-actions"><button className="tennis-secondary" onClick={()=>setResetOpen(false)}>Cancel</button><button className="tennis-primary" disabled={bot.busy||resetBalance<5||resetBalance>1000||!Number.isFinite(resetBalance)||open.length>0||!!session?.pending} onClick={()=>void reset()}>{bot.busy?'Resetting…':'Reset paper run'}</button></div></div></DialogContent></Dialog>
  </div>;
}
